#include<stdio.h>
#include<math.h>
#include<stdbool.h>
#include<stdlib.h>
#include<time.h>

// Min e Max as Lower and Upper bound of the set of numbers to be taken into account
// for the random generation
#define MIN 0
#define MAX 1000

// Function that check the number of tries that a user can do trying to guess a random number generated by the system

void main(){
	
	srand(time(NULL)); // This function prevent the computation of the same number at every execution of the program 
	
	int number;
	int tries = 10;
	int targetNumber = rand() / (RAND_MAX / MAX+1);
	
	 
	
	printf("Welcome to 'Try to Guess the number!'\nInsert a number and guess if it the number computed by the computer.\n");
	printf("The number computer by the computer is between %d and %d\n", MIN, MAX);
	printf("Insert the number and press Enter:\n");
	scanf("%d", &number);
	
	while(tries > 0){
		if(number == targetNumber){
			printf("\nThe number inserted is the right one!\n");
			return;
		} else if(number > targetNumber){
			printf("\nThe number inserted is higher than the right one! Try gain! %d tries remaining.\n", tries);
		} else if(number < targetNumber){
			printf("\nThe number inserted is lower than the right one! Try gain! %d tries remaining.\n", tries);
		}
		tries--;
		scanf("%d", &number);
	}
	return;
}
